script: 'bundle exec rake -t test'
language: ruby
sudo: false

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.7
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - ruby-head
  - jruby-9.2.0.0
  - rubinius-3
matrix:
  exclude:
    - rvm: 2.5.3
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_52.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_52.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_42.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_41.gemfile
  allow_failures:
    - rvm: jruby-9.2.0.0
    - rvm: rubinius-3
    - gemfile: gemfiles/rails_edge.gemfile
gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_edge.gemfile
