script: 'bundle exec rake -t test'
language: ruby
sudo: false

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.3
  - 2.4.1
  - ruby-head
  - jruby-9.1.8.0
  - rubinius-3
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_42.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_41.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_42.gemfile
  allow_failures:
    - rvm: jruby-9.1.8.0
    - rvm: rubinius-3
gemfile:
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_edge.gemfile
